import React from "react";

export const images = {
  Logo1: require("./Logo1.png"),
  Logo2: require("./Logo2.png"),
  Logo3: require("./Logo3.png"),
  Logo4: require("./Logo4.png"),
  Logo: require("./Logo.png"),
  BgImage: require("./Maskgroup.png"),
  Shipping: require("./shipping.png"),
  Safe: require("./safe.png"),
  Price: require("./price.png"),
  BWLogo: require("./bwlogo.jpg"),
  Bg2: require("./bg2.png"),
  Pay1: require("./pay1.png"),
  Pay2: require("./pay2.png"),
  Pay3: require("./pay3.png"),
  Pay4: require("./pay4.png"),
  Review1: require("./review1.png"),
  Review2: require("./review2.png"),
  Review3: require("./review3.png"),
  Product1: require("./product1.png"),
  Product2: require("./product2.png"),
  Product3: require("./product3.png"),
  Product4: require("./product4.png"),
  Bsc:require("./bestsellers.png"),
  Cf:require("./colorfilter.png"),
  Relieve:require("./relieve.png"),
  Aromas:require("./aromas.png"),
  Tcircle:require("./tick-circle.png"),
  Cart:require('./Cart.png'),
  ch1:require('./Iconch1.png'),
  ch2:require('./Iconch2.png'),
  ch3:require('./Iconch3.png'),
  EMT:require('./EMT.png'),
  cover_im1:require('./cover_im1.png'),
  cover_im2:require('./cover_im2.png'),
  cover_im3:require('./cover_im3.png'),
  cover_sm:require('./cover_sm.png'),
};
